# Advanced Statistical and Mathematical Methods: Summative 2

## Section 1: Importing Data

In [44]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Telco_customer_churn.xlsx"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yeanzc/telco-customer-churn-ibm-dataset",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

/var/folders/5d/_70z8cj573dcc1vb6ywm64fh0000gn/T/ipykernel_31257/2258955579.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

In [45]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

## Section 2: Data Cleansing

In [46]:
df.shape

(7043, 33)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

Notes from this: zip code doesn't necessarily need to be a int, calculations should not be done on it, total charges should be a float, suggests data errors

In [48]:
df['Zip Code'] = df['Zip Code'].astype(object)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   object
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(5), object(25)
memory usage: 1.8+ MB

In [50]:
import pandas as pd

df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')

In [51]:
# Checking for null values
df.isnull().any()

CustomerID           False
Count                False
Country              False
State                False
City                 False
Zip Code             False
Lat Long             False
Latitude             False
Longitude            False
Gender               False
Senior Citizen       False
Partner              False
Dependents           False
Tenure Months        False
Phone Service        False
Multiple Lines       False
Internet Service     False
Online Security      False
Online Backup        False
Device Protection    False
Tech Support         False
Streaming TV         False
Streaming Movies     False
Contract             False
Paperless Billing    False
Payment Method       False
Monthly Charges      False
Total Charges         True
Churn Label          False
Churn Value          False
Churn Score          False
CLTV                 False
Churn Reason          True
dtype: bool

Only null value is in churn reason, this is expected as this should be blank for active customers

In [52]:
# View all rows where TotalCharges is null
null_rows = df[df['Total Charges'].isnull()]
print(f"Number of null rows: {len(null_rows)}")
null_rows

Number of null rows: 11

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,NaN,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,NaN,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,NaN,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,NaN,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,NaN,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,NaN,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,NaN,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,NaN,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,NaN,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,NaN,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,NaN,No,0,65,5188,NaN

In [53]:
# Map contract type to number of months
contract_months = {
    'Month-to-Month': 1,
    'One year': 12,
    'Two year': 24
}

# Fill missing TotalCharges = MonthlyCharges * contract length
df['Total Charges'] = df.apply(
    lambda row: row['Monthly Charges'] * contract_months[row['Contract']]
    if pd.isnull(row['Total Charges'])
    else row['Total Charges'],
    axis=1
)

# Verify no nulls remain
print(df['Total Charges'].isnull().sum())

0

In [54]:
# Checking for duplicated records that could skew analysis
df.duplicated(subset=None).any().sum()

0

No duplicated rows so all customers are unique

In [55]:
# Convert all column names to lowercase with underscores
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Verify
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         7043 non-null   object
 1   count              7043 non-null   int64
 2   country            7043 non-null   object
 3   state              7043 non-null   object
 4   city               7043 non-null   object
 5   zip_code           7043 non-null   object
 6   lat_long           7043 non-null   object
 7   latitude           7043 non-null   float64
 8   longitude          7043 non-null   float64
 9   gender             7043 non-null   object
 10  senior_citizen     7043 non-null   object
 11  partner            7043 non-null   object
 12  dependents         7043 non-null   object
 13  tenure_months      7043 non-null   int64
 14  phone_service      7043 non-null   object
 15  multiple_lines     7043 non-null   object
 16  internet_service   7043 non-null   object
 17  online_security    7043 non-null   object
 18  online_backup      7043 non-null   object
 19  device_protection  7043 non-null   object
 20  tech_support       7043 non-null   object
 21  streaming_tv       7043 non-null   object
 22  streaming_movies   7043 non-null   object
 23  contract           7043 non-null   object
 24  paperless_billing  7043 non-null   object
 25  payment_method     7043 non-null   object
 26  monthly_charges    7043 non-null   float64
 27  total_charges      7043 non-null   float64
 28  churn_label        7043 non-null   object
 29  churn_value        7043 non-null   int64
 30  churn_score        7043 non-null   int64
 31  cltv               7043 non-null   int64
 32  churn_reason       1869 non-null   object
dtypes: float64(4), int64(5), object(24)
memory usage: 1.8+ MB

In [56]:
df.drop(columns=['customerid','count', 'lat_long', 'churn_reason', 'country', 'state'], inplace=True)

country and state are removed as they are all in California, USA

In [57]:
print(df['churn_label'].value_counts(normalize=True))

churn_label
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [58]:
numeric_cols = ['tenure_months', 'monthly_charges', 'total_charges', 'churn_score', 'cltv']
df[numeric_cols].describe()

       tenure_months  monthly_charges  total_charges  churn_score         cltv
count    7043.000000      7043.000000    7043.000000  7043.000000  7043.000000
mean       32.371149        64.761692    2281.253259    58.699418  4400.295755
std        24.559481        30.090047    2265.703526    21.525131  1183.057152
min         0.000000        18.250000      18.800000     5.000000  2003.000000
25%         9.000000        35.500000     401.900000    40.000000  3469.000000
50%        29.000000        70.350000    1396.250000    61.000000  4527.000000
75%        55.000000        89.850000    3786.600000    75.000000  5380.500000
max        72.000000       118.750000    8684.800000   100.000000  6500.000000

No obvious errors in terms of impossible values (e.g. tenure < 0). Next check for outliers using IQR

In [59]:
def remove_outliers_iqr(frame, cols):
    clean = frame.copy()
    total_before = len(clean)

    for col in cols:
        # ensure numeric
        clean[col] = pd.to_numeric(clean[col], errors="coerce")

        Q1 = clean[col].quantile(0.25)
        Q3 = clean[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        lower_clamped = max(lower, 0)

        mask_out = (clean[col] < lower_clamped) | (clean[col] > upper)
        out_count = int(mask_out.sum())

        print(f"{col}: lower={lower_clamped:.3f}, upper={upper:.3f}, outliers={out_count}")

        # Keep only rows that are NOT outliers for this column
        clean = clean.loc[~mask_out]

    print(f"Rows before: {total_before}, after: {len(clean)}, removed: {total_before - len(clean)}")
    return clean

# Use the numeric columns you want to trim
iqr_cols = [c for c in numeric_cols]  # your existing list
df = remove_outliers_iqr(df, iqr_cols)
df = df.reset_index(drop=True)

tenure_months: lower=0.000, upper=124.000, outliers=0
monthly_charges: lower=0.000, upper=171.375, outliers=0
total_charges: lower=0.000, upper=8863.650, outliers=0
churn_score: lower=0.000, upper=127.500, outliers=0
cltv: lower=601.750, upper=8247.750, outliers=0
Rows before: 7043, after: 7043, removed: 0

No values are outside the permitted range so all rows are kept

## Section 3: Data Preparation

In [60]:
product_cols = [
    'phone_service', 'multiple_lines', 'internet_service', 
    'online_security', 'online_backup', 'device_protection', 
    'tech_support', 'streaming_tv', 'streaming_movies'
]

# Standardise product columns to Yes/No only
df['multiple_lines'] = df['multiple_lines'].replace('No phone service', 'No')
df['internet_service'] = df['internet_service'].replace({'DSL': 'Yes', 'Fiber optic': 'Yes'})

# Replace 'No internet service' with 'No' for all affected columns
no_internet_cols = [
    'online_security', 'online_backup', 'device_protection',
    'tech_support', 'streaming_tv', 'streaming_movies'
]
for col in no_internet_cols:
    df[col] = df[col].replace('No internet service', 'No')

# Verify
for col in product_cols:
    print(f"{col}: {df[col].unique()}")

phone_service: ['Yes' 'No']
multiple_lines: ['No' 'Yes']
internet_service: ['Yes' 'No']
online_security: ['Yes' 'No']
online_backup: ['Yes' 'No']
device_protection: ['No' 'Yes']
tech_support: ['No' 'Yes']
streaming_tv: ['No' 'Yes']
streaming_movies: ['No' 'Yes']

In [61]:
df['product_count'] = (df[product_cols] == 'Yes').sum(axis=1)

print(df['product_count'].value_counts().sort_index())

product_count
1    1264
2     859
3     846
4     965
5     922
6     908
7     676
8     395
9     208
Name: count, dtype: int64

#### Validating other categorical values

In [62]:
non_product_categories = ['gender', 'senior_citizen', 'partner', 'dependents', 'paperless_billing', 'contract', 'payment_method']

for col in non_product_categories:
    print(f"{col}: {df[col].unique()}")

gender: ['Male' 'Female']
senior_citizen: ['No' 'Yes']
partner: ['No' 'Yes']
dependents: ['No' 'Yes']
paperless_billing: ['Yes' 'No']
contract: ['Month-to-month' 'Two year' 'One year']
payment_method: ['Mailed check' 'Electronic check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

All standardised i.e. no typos, capitalisation inconsistencies or unexpected categories. Data is clean

## Section 4: Exploratory Data Analysis

### Section 4a: Relationship between contract lengths and CLV

### Section 4b: Relationship between payment and billing methods and CLV

### Section 4c: Relationship between customer's geographic location and CLV

### Section 4d: Relationship between family setup and CLV

### Section 4e: Distribution of product count

- needed to define where the low, medium and high boundaries should be

# Section 5: Manually Calculated ANOVA

## Section 6: Using the ANOVA library